# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grSim_Data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grSim_Data.proto',
  package='',
  serialized_pb=_b('\n\x10grSim_Data.proto\"\x88\x01\n\x11grSim_Robot_Datum\x12\n\n\x02id\x18\x01 \x02(\r\x12\x0e\n\x06wheel1\x18\x02 \x02(\r\x12\x0e\n\x06wheel2\x18\x03 \x02(\r\x12\x0e\n\x06wheel3\x18\x04 \x02(\r\x12\x0e\n\x06wheel4\x18\x05 \x02(\r\x12\x14\n\x0ckicker_ready\x18\x06 \x02(\x08\x12\x11\n\thave_ball\x18\x07 \x02(\x08\"]\n\ngrSim_Data\x12\x11\n\ttimestamp\x18\x01 \x02(\x01\x12\x14\n\x0cisteamyellow\x18\x02 \x02(\x08\x12&\n\nrobot_data\x18\x03 \x03(\x0b\x32\x12.grSim_Robot_Datum')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GRSIM_ROBOT_DATUM = _descriptor.Descriptor(
  name='grSim_Robot_Datum',
  full_name='grSim_Robot_Datum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grSim_Robot_Datum.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wheel1', full_name='grSim_Robot_Datum.wheel1', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wheel2', full_name='grSim_Robot_Datum.wheel2', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wheel3', full_name='grSim_Robot_Datum.wheel3', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wheel4', full_name='grSim_Robot_Datum.wheel4', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kicker_ready', full_name='grSim_Robot_Datum.kicker_ready', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='have_ball', full_name='grSim_Robot_Datum.have_ball', index=6,
      number=7, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=157,
)


_GRSIM_DATA = _descriptor.Descriptor(
  name='grSim_Data',
  full_name='grSim_Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='grSim_Data.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isteamyellow', full_name='grSim_Data.isteamyellow', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='robot_data', full_name='grSim_Data.robot_data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=252,
)

_GRSIM_DATA.fields_by_name['robot_data'].message_type = _GRSIM_ROBOT_DATUM
DESCRIPTOR.message_types_by_name['grSim_Robot_Datum'] = _GRSIM_ROBOT_DATUM
DESCRIPTOR.message_types_by_name['grSim_Data'] = _GRSIM_DATA

grSim_Robot_Datum = _reflection.GeneratedProtocolMessageType('grSim_Robot_Datum', (_message.Message,), dict(
  DESCRIPTOR = _GRSIM_ROBOT_DATUM,
  __module__ = 'grSim_Data_pb2'
  # @@protoc_insertion_point(class_scope:grSim_Robot_Datum)
  ))
_sym_db.RegisterMessage(grSim_Robot_Datum)

grSim_Data = _reflection.GeneratedProtocolMessageType('grSim_Data', (_message.Message,), dict(
  DESCRIPTOR = _GRSIM_DATA,
  __module__ = 'grSim_Data_pb2'
  # @@protoc_insertion_point(class_scope:grSim_Data)
  ))
_sym_db.RegisterMessage(grSim_Data)


# @@protoc_insertion_point(module_scope)
