# float 64 pose_point_x
# float 64 pose_point_y
# float 64 pose_point_z
# float 64 pose_quat_x
# float 64 pose_quat_y
# float 64 pose_quat_z
# float 64 pose_quat_w
# float 64 twist_lin_x
# float 64 twist_lin_y
# float 64 twist_lin_z
# float 64 twist_ang_x
# float 64 twist_ang_y
# float 64 twist_ang_z

# geometry messages
geometry_msgs/Pose pose
geometry_msgs/Twist twist1
geometry_msgs/Twist twist2
geometry_msgs/Twist twist3
geometry_msgs/Twist twist4
geometry_msgs/Twist twist5
geometry_msgs/Twist twist6